global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']
        labels:
          application: 'auth-service'

  # Upload Service
  - job_name: 'upload-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['upload-service:8083']
        labels:
          application: 'upload-service'

  # Tags Generation Service
  - job_name: 'tags-generation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tags-generation-service:8082']
        labels:
          application: 'tags-generation-service'

  # Search Service
  - job_name: 'search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-service:8085']
        labels:
          application: 'search-service'

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8084']
        labels:
          application: 'payment-service'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8086']
        labels:
          application: 'notification-service'