apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsync-search-service
  template:
    metadata:
      labels:
        app: cloudsync-search-service
    spec:
      containers:
        - name: cloudsync-search-service-container
          image: sujalsharma/search-service:latest
          ports:
            - containerPort: 8085
          env:
            # THIS IS THE FIX:
            # Tell Spring Boot where to find the config file.
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.yaml" 
          
          envFrom:
            # This loads your database password, JWT secret, etc.
            - secretRef:
                name: search-service-secret
          
          volumeMounts:
            # Mount the config file to the path we specified above
            - name: config-volume
              mountPath: /config/application.yaml
              subPath: application.yaml
              
      volumes:
        # Define the volume from the ConfigMap
        - name: config-volume
          configMap:
            name: search-service-config
            items:
              - key: application.yaml
                path: application.yaml
                
