apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsync-upload-service
  template:
    metadata:
      labels:
        app: cloudsync-upload-service
    spec:
      containers:
        - name: cloudsync-upload-service-container
          image: sujalsharma/upload-download-rag-pipelin:latest
          ports:
            - containerPort: 8083
          env:
            # THIS IS THE FIX:
            # Tell Spring Boot where to find the config file.
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.yaml" 
          
          envFrom:
            # This loads your database password, JWT secret, etc.
            - secretRef:
                name: upload-service-secret
          
          volumeMounts:
            # Mount the config file to the path we specified above
            - name: config-volume
              mountPath: /config/application.yaml
              subPath: application.yaml
              
      volumes:
        # Define the volume from the ConfigMap
        - name: config-volume
          configMap:
            name: upload-service-configmap
            items:
              - key: application.yaml
                path: application.yaml
                
